name: angel
description: An easily-extensible web server framework in Dart.
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.0.0-dev <3.0.0'
homepage: https://github.com/angel-dart/angel
dependencies:
  angel_auth: ^1.1.0 # Supports stateless authentication via JWT
  angel_configuration: ^1.1.0 # Loads application configuration, along with support for .env files.
  angel_cors: ^1.0.0 # CORS support
  angel_framework: ^1.1.0 # The core server library.
  angel_jael: ^1.0.0 # Server-side templating engine
  angel_static: ^1.3.0 # Static file server
  angel_validate: ^1.0.0 # Allows for validation of input data
  dart2_constant: ^1.0.0 # For backwards compatibility.
dev_dependencies:
  angel_hot: ^1.1.0 # Hot-reloading support. :)
  angel_test: ^1.1.0 # Utilities for testing Angel servers.
  console: ^3.0.0
  test: ^0.12.13
