name: fibonacci
description: A microservice that simply computes a Fibonacci number.
publish_to: none
dependencies:
  angel_auth: ^1.0.0
  angel_configuration: ^1.2.0-rc.0
  angel_framework: ^1.0.0
  my_api_client:
    path: ../my_api_client